# yamllint disable rule:line-length
---
name: setup environment

description: load values from 1password vault

inputs:

  flag:
    description: input value that can be used to control which actions are run
    required: false
    default: ""

runs:
  using: "composite"

  steps:

    - name: load values from 1password
      uses: 1password/load-secrets-action@v3
      with:
        export-env: true
      env:
        SLACK_BOT_TOKEN: op://platform/svc-slack/platform-slack-bot-token
        GH_TOKEN: op://platform/svc-github/access-token
        DOCKER_LOGIN: op://platform/svc-github/username
        DOCKER_PASSWORD: op://platform/svc-github/access-token
        COSIGN_PASSWORD: op://platform/svc-cosign/passphrase
        COSIGN_SIGN_KEY: op://platform/svc-cosign-private-key/notesPlain
        COSIGN_VERIFY_KEY: platform/svc-cosign-public-key/notesPlain

    - name: Set signing key files
      shell: bash
      run: |
        echo "${COSIGN_SIGN_KEY}" > cosign.key
        echo "${COSIGN_VERIFY_KEY}" > cosign.pub
        echo "pubic key"
        cat cosign.pub
